apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # Replace with your ECR URL: terraform output ecr_frontend_url
          image: 981548928508.dkr.ecr.us-east-1.amazonaws.com/task-manager-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              value: backend
            - name: BACKEND_PORT
              value: "8000"
          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              cpu: "512m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
