env: prod

ingress:
  enabled: true
  hostname: prod.oybek.xyz

backend:
  replicas: 2
  nodeSelector:
    environment: prod
  resources:
    requests:
      cpu: "256m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

frontend:
  replicas: 2
  nodeSelector:
    environment: prod
  resources:
    requests:
      cpu: "256m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

autoscaling:
  enabled: true
  backend:
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  frontend:
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
